### ISSUE TITLE
how to use it.

### ISSUE THREAD

**Issue by qadirsuh** [anaisbetts/node-system-idle-time#8]
I am on mac. how to use it. I have uploaded it to heroku. does this logs any thing after some idle time.

Please tell me how can I use it ?

**Comment by ankur1163** [comment]
did you get answer for this? There is no documentaton on how to use this thing?

**Comment by tance77** [comment]
See this PR https://github.com/paulcbetts/node-system-idle-time/pull/9/commits/c0a09de355691478b6f39ea12b2aff812df76803

**Comment by ankur1163** [comment]
Thanks man

**Comment by DivekJohns** [comment]
there is an inbuilt [Electron Power monitor API's][1] 

    const {powerMonitor} = require('electron'); 
    const idle = powerMonitor.getSystemIdleTime() // it returns in seconds when I am writing this
    console.log('Current System Idle Time - ', idle); 


  [1]: https://www.electronjs.org/docs/api/power-monitor
